import test from 'node:test';
import assert from 'node:assert/strict';
import { createInference, validateAnalysis, validateChat, retryDelay } from '../../src/lib/learning/model.ts';
const input={prompt:'비교',choice:'A',reason:'A의 값이 더 작기 때문입니다.',expected:'A',scope:'비교',activities:[{id:'compare',title:'비교'}]};
const result={interpretation:'understood',evidence:'값이 더 작기',note:'조건을 비교했습니다.',activity_id:null};
test('understanding goes to a transfer check, not compulsory remediation',()=>assert.equal(validateAnalysis(result,input).recommendation,'transfer_check'));
test('model cannot override deterministic correctness',()=>assert.equal(validateAnalysis(result,{...input,choice:'B'}).recommendation,'conflicting_evidence_review'));
for(const change of [{interpretation:'diagnosed'},{evidence:'학생이 쓰지 않은 문장'},{evidence:''},{activity_id:'arbitrary'}])test('rejects unsupported analysis '+JSON.stringify(change),()=>assert.throws(()=>validateAnalysis({...result,...change},input)));
test('uncertainty is distinct from model failure',()=>assert.equal(validateAnalysis({...result,interpretation:'uncertain',evidence:''},input).recommendation,'clarification'));
test('unsupported chat prose is replaced by deterministic abstention',()=>assert.ok(!validateChat({answer:'근거 없이 100% 확실합니다',supported:false,citations:[]},[]).answer.includes('100%')));
const chunk={id:'c',material_id:'m',version:2,content:'물의 밀도는 1이다.'};
test('chat retains material and immutable source version',()=>assert.deepEqual(validateChat({answer:'밀도',supported:true,citations:[{id:'c',quote:'밀도는 1'}]},[chunk]).sources,[{material_id:'m',version:2,quote:'밀도는 1'}]));
for(const citations of [[],[{id:'bad',quote:'밀도는 1'}],[{id:'c',quote:'가짜'}],[{id:'c',quote:'밀도는 1'},{id:'c',quote:'밀도는 1'}]])test('rejects citation violation '+JSON.stringify(citations),()=>assert.throws(()=>validateChat({answer:'x',supported:true,citations},[chunk])));
const config={endpoint:'https://provider.example/v1/chat/completions',key:'not-a-real-key',model:'test'};
test('explicit HTTPS endpoint only',()=>assert.throws(()=>createInference({...config,endpoint:'http://provider.example'})));
test('JSON provider contract with no tools and no redirects',async()=>{let request;const infer=createInference(config,async(url,opts)=>{request=opts;return Response.json({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}]});});assert.deepEqual(await infer('policy',{data:'학생'}),{ok:true});assert.equal(request.redirect,'error');assert.equal(JSON.parse(request.body).tools,undefined);});
for(const status of [400,401,403,429,500,503])test('provider status '+status,async()=>{const infer=createInference(config,async()=>new Response('',{status,headers:{'retry-after':'60'}}));await assert.rejects(infer('s',{}),e=>e.retryable===(status===429||status>=500));});
test('oversized provider output is rejected',async()=>{await assert.rejects(createInference(config,async()=>new Response('x'.repeat(65537)))('s',{}),e=>e.code==='model_output_limit');});
test('truncated answer is not accepted',async()=>{await assert.rejects(createInference(config,async()=>Response.json({choices:[{message:{content:'{}'},finish_reason:'length'}]}))('s',{}),e=>e.code==='model_incomplete');});
test('caller cancellation reaches provider',async()=>{const c=new AbortController();c.abort();await assert.rejects(createInference(config,async(u,o)=>{assert.equal(o.signal.aborted,true);throw Error('aborted');})('s',{},c.signal),e=>e.code==='model_timeout');});
test('retry backoff is bounded',()=>{assert.equal(retryDelay(1,0,()=>0.5),2000);assert.equal(retryDelay(3,60000,()=>0.5),60000);assert.equal(retryDelay(99,999999,()=>0.5),300000);});
