import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,users,sql,act,list,claim,finish,packs,literal,asUser} from './fixtures.mjs';
import {transition,defineContentPack} from '../../src/lib/learning/workflow.mjs';
let c1,c2;const t=users.teacher,s=users.student;
function setup(pack=packs[0]){({c1,c2}=fixture());const assignment=act(t,'activate_pack',c1,null,{pack_id:pack.id,pack_version:pack.version,reviewed:true});return {assignment,pack};}
function submit(a,pack,request){return act(s,'submit',a,null,{answer:pack.correctAnswer,reason:'학습 근거 설명'},request);}
function analysis(j){return {interpretation:'understood',evidence:'supported',quote:j.response.reason,note:'확인 질문',ruleVerdict:'correct',model:'test',proposal:{kind:'transfer_check'}};}
for(const pack of packs)test(`${pack.id} full persistent workflow mirrors kernel`,()=>{
 const {assignment}=setup(pack);const id=submit(assignment,pack);const job=claim();assert.equal(finish(job,analysis(job)),'t');
 let record={id,classId:c1,studentId:s,packId:pack.id,packVersion:pack.version,version:1,stage:'awaiting_review'};
 for(const [action,role,data] of [['assign_activity','teacher',{activity_id:pack.activities[0].id,feedback:'직접 비교해 봐요'}],['complete_activity','student',{observation:'조건을 비교',explanation:'설명을 바꿨어요'}],['submit_transfer','student',{answer:pack.transfer.correctAnswer,reason:'새 조건에도 같은 원리'}],['complete','teacher',{feedback:'근거를 확인했습니다'}]]){
  const user=role==='teacher'?t:s;act(user,action,id,record.version,data);
  record=transition(record,{recordId:id,expectedVersion:record.version,action,activityId:data.activity_id},{userId:user,role,classIds:[c1]},defineContentPack(pack));
  const actual=list(user,c1).attempts[0];assert.equal(actual.stage,record.stage);assert.equal(actual.version,record.version);
 }
 assert.equal(record.stage,'completed');assert.equal(Number(sql(`select count(*) from private.learning_events where attempt_id='${id}'`)),6);
});
test('normal understanding skips compulsory remediation',()=>{const {assignment,pack}=setup();const id=submit(assignment,pack);act(t,'confirm_understanding',id,1,{feedback:'근거가 적절해요'});assert.equal(list(s,c1).attempts[0].stage,'awaiting_transfer');assert.equal(list(s,c1).attempts[0].activity_id,null);});
test('same request replay returns same ID even after teacher changes record',()=>{const {assignment,pack}=setup();const q=crypto.randomUUID(),id=submit(assignment,pack,q);act(t,'confirm_understanding',id,1,{feedback:'좋아요'});assert.equal(submit(assignment,pack,q),id);assert.equal(list(s,c1).attempts.length,1);assert.throws(()=>act(s,'submit',assignment,null,{answer:pack.correctAnswer,reason:'다른 내용'},q));});
test('student cannot activate a pack or approve their own answer',()=>{const {assignment,pack}=setup();assert.throws(()=>act(s,'activate_pack',c1,null,{pack_id:pack.id,pack_version:pack.version,reviewed:true}));const id=submit(assignment,pack);assert.throws(()=>act(s,'confirm_understanding',id,1,{feedback:'셀프 승인'}));});
test('teacher must explicitly acknowledge content review',()=>{setup();assert.throws(()=>act(t,'activate_pack',c1,null,{pack_id:packs[1].id,pack_version:packs[1].version,reviewed:false}));});
test('cross-course list and action denied, same-course peers cannot see answers',()=>{const {assignment,pack}=setup();const id=submit(assignment,pack);assert.throws(()=>list(users.outsider,c1));assert.equal(list(users.other,c1).attempts.length,0);assert.throws(()=>act(users.other,'resubmit',id,1,{answer:pack.correctAnswer,reason:'타인 답안'}));});
test('student cannot call private tables, worker or pack administration RPC',()=>{setup();for(const statement of ['select * from private.learning_attempts','select public.learning_claim()',`select public.learning_register_pack('{}'::jsonb)`])assert.throws(()=>asUser(s,statement));});
test('anon cannot read course membership or invoke commands',()=>{setup();assert.throws(()=>sql('set role anon;select public.learning_home()'));});
test('direct RPC choice validation cannot be bypassed',()=>{const {assignment}=setup();assert.throws(()=>act(s,'submit',assignment,null,{answer:'목록 밖 답',reason:'근거'}));assert.throws(()=>act(s,'submit',assignment,null,{answer:null,reason:'근거'}));});
test('stale/null versions and invalid activities rejected',()=>{const {assignment,pack}=setup();const id=submit(assignment,pack);for(const version of [null,0,2])assert.throws(()=>act(t,'confirm_understanding',id,version,{feedback:'검토'}));assert.throws(()=>act(t,'assign_activity',id,1,{activity_id:'unknown',feedback:'검토'}));});
test('transfer content and analysis are absent from student pre-approval view',()=>{const {assignment,pack}=setup();submit(assignment,pack);const j=claim();finish(j,analysis(j));const row=list(s,c1).attempts[0];assert.equal(row.transfer,null);assert.equal(row.activity,null);assert.equal(row.activities,null);assert.equal('analysis' in row,false);assert.deepEqual(list(s,c1).catalog,[]);assert.ok(list(t,c1).attempts[0].analysis);});
test('teacher review fences late inference',()=>{const {assignment,pack}=setup();const id=submit(assignment,pack);const j=claim();act(t,'confirm_understanding',id,1,{feedback:'직접 확인'});assert.equal(finish(j,analysis(j)),'f');assert.equal(list(t,c1).attempts[0].analysis,null);});
test('worker handles revoked enrollment on finish and on claim',()=>{const {assignment,pack}=setup();submit(assignment,pack);const j=claim();sql(`update private.learning_enrolments set active=false where user_id='${s}'`);assert.equal(finish(j,analysis(j)),'f');assert.equal(sql(`select status from private.learning_jobs where id='${j.id}'`),'cancelled');});
test('lease expiry cannot be completed by old worker',()=>{const {assignment,pack}=setup();submit(assignment,pack);const j=claim();sql(`update private.learning_jobs set lease_until=now()-interval '1 second' where id='${j.id}'`);assert.equal(finish(j,analysis(j)),'f');const next=claim();assert.notEqual(next.lease,j.lease);assert.equal(finish(next,analysis(next)),'t');});
test('provider retry has a bounded attempt budget',()=>{const {assignment,pack}=setup();submit(assignment,pack);for(let i=0;i<3;i++){const j=claim();assert.ok(j);finish(j,null,'timeout',true);sql(`update private.learning_jobs set available_at=now()-interval '1 second' where id='${j.id}'`);}assert.equal(claim(),null);assert.equal(list(t,c1).attempts[0].job.status,'failed');});
test('crashed workers become terminal rather than infinite processing',()=>{const {assignment,pack}=setup();submit(assignment,pack);for(let i=0;i<3;i++){const j=claim();sql(`update private.learning_jobs set lease_until=now()-interval '1 second' where id='${j.id}'`);}assert.equal(claim(),null);assert.equal(list(t,c1).attempts[0].job.error_code,'attempts_exhausted');});
test('quota defers job with an explicit available time',()=>{const {assignment,pack}=setup();submit(assignment,pack);sql(`update private.learning_courses set daily_calls=0 where id='${c1}'`);assert.equal(claim(),null);const job=list(s,c1).attempts[0].job;assert.equal(job.error_code,'quota');assert.equal(job.status,'retry_wait');assert.ok(Date.parse(job.available_at)>Date.now());});
test('resubmission preserves original evidence in audit log and queues new input version',()=>{const {assignment,pack}=setup();const id=submit(assignment,pack);act(t,'request_clarification',id,1,{feedback:'더 설명해 봐요'});act(s,'resubmit',id,2,{answer:pack.correctAnswer,reason:'새 설명'});const j=claim();assert.equal(j.input_version,3);assert.equal(j.response.reason,'새 설명');assert.equal(sql(`select snapshot#>>'{response,reason}' from private.learning_events where attempt_id='${id}' and action='resubmit'`),'학습 근거 설명');});
test('duplicate completion and forged evidence fail closed',()=>{const {assignment,pack}=setup();submit(assignment,pack);const j=claim();assert.throws(()=>finish(j,{...analysis(j),quote:'존재하지 않음'}));assert.equal(finish(j,analysis(j)),'t');assert.equal(finish(j,analysis(j)),'f');});
test('pack versions cannot be overwritten',()=>{setup();assert.throws(()=>sql(`select public.learning_register_pack(${literal(JSON.stringify({...packs[0],title:'변경'}))}::jsonb)`));});
