import test from 'node:test';import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {fixture,users,sql,act,list,claim,finish,literal,asUser,packs} from './fixtures.mjs';
import {catalogRecords} from '../../src/lib/mcp/catalog.mjs';
const t=users.teacher,s=users.student;
function setup(){const {c1,c2}=fixture();const assignment=act(t,'activate_pack',c1,null,{pack_id:packs[0].id,pack_version:packs[0].version,reviewed:true});const id=act(s,'submit',assignment,null,{answer:packs[0].correctAnswer,reason:'물체와 물의 밀도를 비교해요.'});return {c1,c2,id,assignment};}
function command(user,action,id,revision=1,data={},request=crypto.randomUUID()){
 const payload={resource_id:'phet-buoyancy',resource_version:'1.0.0',reviewed:true,attempt_version:1,...data};
 return asUser(user,`select public.learning_resource_act(${literal(action)},${literal(id)}::uuid,${revision===null?'null':revision},${literal(JSON.stringify(payload))}::jsonb,${literal(request)}::uuid)`);
}
test('directory migration data matches code including metadata and pack mappings',()=>{for(const {packIds,...r} of catalogRecords){const stored=JSON.parse(sql(`select definition from private.learning_resource_catalog where id=${literal(r.id)} and version=${literal(r.version)}`));assert.deepEqual(stored,r);}});
test('students receive no recommendation candidates or MCP trace before teacher sharing',()=>{const {c1}=setup();const teacher=list(t,c1).attempts[0],student=list(s,c1).attempts[0];assert.equal(teacher.resource_candidates.length,1);assert.equal('resource_candidates'in student,false);assert.deepEqual(student.shared_resources,[]);assert.equal('analysis'in student,false);});
test('explicit teacher review delivers canonical URL without mutating learning state or cancelling AI lease',()=>{const {c1,id}=setup();const job=claim();command(t,'share_resource',id);const row=list(t,c1).attempts[0];assert.equal(row.version,1);assert.equal(row.resource_revision,2);assert.equal(row.job.status,'running');assert.equal(row.stage,'awaiting_review');const student=list(s,c1).attempts[0];assert.equal(student.shared_resources[0].url,catalogRecords[0].url);assert.equal(finish(job,{interpretation:'understood',evidence:'supported',quote:job.response.reason,note:'확인',ruleVerdict:'correct',model:'test'}),'t');});
test('student, peer and other-course member cannot share or revoke',()=>{const {id}=setup();for(const user of [s,users.other,users.outsider])for(const action of ['share_resource','revoke_resource'])assert.throws(()=>command(user,action,id));});
test('another teacher cannot cross course boundary',()=>{const {id,c2}=setup();sql(`update private.learning_enrolments set role='teacher' where course_id=${literal(c2)}`);assert.throws(()=>command(users.outsider,'share_resource',id));});
test('review flag, injected URL and unrelated resources rejected by DIRECT RPC',()=>{const {id}=setup();for(const data of [{reviewed:false},{reviewed:'true'},{url:'https://evil.invalid'},{resource_id:'khan-fractions'},{resource_version:'2.0.0'}])assert.throws(()=>command(t,'share_resource',id,1,data));});
test('stale resource revision and stale answer revision are independent fences',()=>{const {id}=setup();assert.throws(()=>command(t,'share_resource',id,null));assert.throws(()=>command(t,'share_resource',id,1,{attempt_version:2}));command(t,'share_resource',id);assert.throws(()=>command(t,'revoke_resource',id,1));});
test('same request ID replays once; changed payload conflicts and replay cannot resurrect a revoked share',()=>{const {id,c1}=setup();const key=crypto.randomUUID();assert.equal(command(t,'share_resource',id,1,{},key),id);assert.equal(command(t,'share_resource',id,1,{},key),id);assert.throws(()=>command(t,'share_resource',id,1,{reviewed:false},key));command(t,'revoke_resource',id,2);assert.equal(command(t,'share_resource',id,1,{},key),id);assert.deepEqual(list(s,c1).attempts[0].shared_resources,[]);assert.equal(Number(sql(`select count(*) from private.learning_events where attempt_id=${literal(id)} and action='share_resource'`)),1);});
test('revoked teacher membership is checked before acknowledging a replay',()=>{const {id}=setup();const key=crypto.randomUUID();command(t,'share_resource',id,1,{},key);sql(`update private.learning_enrolments set active=false where user_id=${literal(t)}`);assert.throws(()=>command(t,'share_resource',id,1,{},key));});
test('new answer retires prior input resource deliveries',()=>{const {id,c1}=setup();command(t,'share_resource',id);act(t,'request_clarification',id,1,{feedback:'이유를 보완해 주세요.'});act(s,'resubmit',id,2,{answer:packs[0].correctAnswer,reason:'새롭게 보완한 근거'});assert.deepEqual(list(s,c1).attempts[0].shared_resources,[]);assert.equal(Number(sql(`select count(*) from private.learning_resource_shares where attempt_id=${literal(id)}`)),1);});
test('catalog disable immediately hides existing share; metadata itself is immutable',()=>{const {id,c1}=setup();command(t,'share_resource',id);try{sql("update private.learning_resource_catalog set enabled=false where id='phet-buoyancy'");assert.deepEqual(list(s,c1).attempts[0].shared_resources,[]);assert.throws(()=>command(t,'share_resource',id,2));assert.throws(()=>sql("update private.learning_resource_catalog set definition=jsonb_set(definition,'{url}','\"https://evil.invalid\"') where id='phet-buoyancy'"));}finally{sql("update private.learning_resource_catalog set enabled=true where id='phet-buoyancy'");}});
test('inactive student or assignment blocks new sharing',()=>{const {id,assignment}=setup();sql(`update private.learning_assignments set active=false where id=${literal(assignment)}`);assert.throws(()=>command(t,'share_resource',id));sql(`update private.learning_assignments set active=true where id=${literal(assignment)}`);sql(`update private.learning_enrolments set active=false where user_id=${literal(s)}`);assert.throws(()=>command(t,'share_resource',id));});
test('private table and legacy view privileges cannot bypass session RPC',()=>{const {c1}=setup();for(const query of ['select * from private.learning_resource_catalog','select * from private.learning_resource_shares',`select private.learning_list_v1(${literal(c1)}::uuid,null,null)`])assert.throws(()=>asUser(s,query));assert.throws(()=>sql('set role anon;select public.learning_resource_act(null,null,null,null,null)'));});
test('simultaneous duplicate deliveries have one effect and identical acknowledgement',async()=>{const {id}=setup();const key=crypto.randomUUID();const payload={resource_id:'phet-buoyancy',resource_version:'1.0.0',reviewed:true,attempt_version:1};const statement=`begin;set local role authenticated;select set_config('request.jwt.claim.sub',${literal(t)},true);select public.learning_resource_act('share_resource',${literal(id)}::uuid,1,${literal(JSON.stringify(payload))}::jsonb,${literal(key)}::uuid);commit;`;const run=()=>promisify(execFile)('psql',[process.env.TEST_DATABASE_URL,'-X','-v','ON_ERROR_STOP=1','-Atq','-c',statement]);const results=await Promise.all([run(),run()]);for(const result of results)assert.equal(result.stdout.trim().split('\n').at(-1),id);assert.equal(Number(sql(`select count(*) from private.learning_resource_shares where attempt_id=${literal(id)}`)),1);});
